apiVersion: apps/v1
kind: Deployment
metadata:
    name: microfrontend-demo2
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: microfrontend-demo2
    template:
        metadata:
            labels:
                app: microfrontend-demo2
        spec:
            containers:
                -   name: mashroom-portal
                    image: gcr.io/${PROJECT_ID}/microfrontend-demo2:${npm_package_version}
                    imagePullPolicy: Always
                    env:
                        -   name: NODE_ENV
                            value: production
                    resources:
                        requests:
                            cpu: 100m
                            memory: 80Mi
                    ports:
                        -   containerPort: 6089
                    readinessProbe:
                        httpGet:
                            path: /api/ready
                            port: 6089
                        initialDelaySeconds: 2
                        periodSeconds: 60
