{
 "title": "Mashroom Portal",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "95% of Requests Served Within",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mashroom_http_request_duration_seconds_bucket{service=\"mashroom-portal\"}[5m])) by (le)) * 1000",
     "legendFormat": "All Routes"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mashroom_http_requests_total{service=\"mashroom-portal\"}[5m]))",
     "legendFormat": "All Routes"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mashroom_http_requests_total{status=\"500\", service=\"mashroom-portal\"}[5m]))",
     "legendFormat": "HTTP 500"
    },
    {
     "expr": "sum(rate(mashroom_http_requests_total{status=\"404\", service=\"mashroom-portal\"}[5m]))",
     "legendFormat": "HTTP 404"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=\"mashroom-portal\"} / 1024 / 1024",
     "legendFormat": "Heap Total {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{service=\"mashroom-portal\"} / 1024 / 1024",
     "legendFormat": "Heap Used {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "avg(irate(process_cpu_seconds_total{service=\"mashroom-portal\"}[5m])) by (pod) * 100",
     "legendFormat": "Total {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_memory_cache_hit_ratio{service=\"mashroom-portal\"}",
     "legendFormat": "Hit Ratio {{pod}}"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_sessions_total{service=\"mashroom-portal\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Portal HTTP Proxy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_http_proxy_http_pool_connections_active_total{service=\"mashroom-portal\"}",
     "legendFormat": "HTTP Pool Active"
    },
    {
     "expr": "mashroom_http_proxy_http_pool_connections_idle_total{service=\"mashroom-portal\"}",
     "legendFormat": "HTTP Pool Idle"
    },
    {
     "expr": "mashroom_http_proxy_https_pool_connections_active_total{service=\"Mashroom\"}",
     "legendFormat": "HTTPS Pool Active"
    },
    {
     "expr": "mashroom_http_proxy_https_pool_connections_idle_total{service=\"Mashroom\"}",
     "legendFormat": "HTTPS Pool Idle"
    },
    {
     "expr": "mashroom_http_proxy_ws_connections_active_total{service=\"Mashroom\"}",
     "legendFormat": "WS Connections"
    }
   ]
  },
  {
   "title": "WebSocket Connections (Messaging)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_websocket_connections_total{service=\"mashroom-portal\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_plugins_loaded_total{service=\"mashroom-portal\"}",
     "legendFormat": "Loaded {{pod}}"
    },
    {
     "expr": "mashroom_plugins_error_total{service=\"mashroom-portal\"}",
     "legendFormat": "Error {{pod}}"
    }
   ]
  },
  {
   "title": "Remote Portal Apps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mashroom_remote_apps_k8s_total{service=\"mashroom-portal\"}",
     "legendFormat": "Total {{pod}}"
    },
    {
     "expr": "mashroom_remote_apps_k8s_error_total{service=\"mashroom-portal\"}",
     "legendFormat": "Error {{pod}}"
    },
    {
     "expr": "mashroom_remote_apps_k8s_connection_timeout_total{service=\"mashroom-portal\"}",
     "legendFormat": "Connection Timeout {{pod}}"
    }
   ]
  },
  {
   "title": "MongoDB Storage Connected ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mashroom_storage_mongodb_connected{service=\"mashroom-portal\"}"
    }
   ]
  },
  {
   "title": "Redis Session Connected ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mashroom_sessions_redis_nodes_connected{service=\"mashroom-portal\"}"
    }
   ]
  },
  {
   "title": "Redis Memory Cache Connected ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mashroom_memory_cache_redis_nodes_connected{service=\"mashroom-portal\"}"
    }
   ]
  }
 ]
}